In [2]:
from hta.trace_analysis import TraceAnalysis
import polars as pl
import pandas as pd
import glob

Couldn't parse gemma train.

In [3]:
dfs = []
for path in glob.glob("/proj/threadtune-PG0/amir/kineto_traces/*"):
    analyzer = TraceAnalysis({0: "device.0.json"}, path)
    rank = 0
    trace_data = analyzer.t.get_trace(rank)
    symbol_table = analyzer.t.symbol_table.get_sym_table()
    dfs.append(
        pl.concat(
            pl.from_pandas(trace_data[trace_data["stream"] != -1])
            .select(pl.lit(rank).alias("rank"), pl.all())
            for rank, trace_data in analyzer.t.traces.items()
        ).join(
            pl.from_dict({"name": list(range(len(symbol_table))), "s_name": symbol_table}),
            on="name",
        )
    )
dfs

Parsed /proj/threadtune-PG0/amir/kineto_traces/deit-train/device.0.json time = 0.24 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/deit-train/device.0.json backend=json in 0.48 seconds; current PID:170154
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/deit-train/device.0.json in 0.54 seconds; current PID:170154
leaving parse_multiple_ranks duration=0.55 seconds
leaving parse_traces duration=0.55 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/gpt2-inference/device.0.json time = 0.03 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/gpt2-inference/device.0.json backend=json in 0.11 seconds; current PID:170154
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/gpt2-inference/device.0.json in 0.14 seconds; current PID:170154
leaving parse_multiple_ranks duration=0.15 seconds
leaving parse_traces duration=0.15 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/bloom-train/device.0.json time = 0.02 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/bloom-train/device.0.json backend=json in 0.08 seconds; current PID:170154
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/bloom-train/device.0.json in 0.11 seconds; current PID:170154
leaving parse_multiple_ranks duration=0.11 seconds
leaving parse_traces duration=0.11 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/resnet50-train/device.0.json time = 0.14 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/resnet50-train/device.0.json backend=json in 0.32 seconds; current PID:170154
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/resnet50-train/device.0.json in 0.44 seconds; current PID:170154
leaving parse_multiple_ranks duration=0.45 seconds
leaving parse_traces duration=0.45 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/gpt2-train/device.0.json time = 0.18 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/gpt2-train/device.0.json backend=json in 0.37 seconds; current PID:170154
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/gpt2-train/device.0.json in 0.43 seconds; current PID:170154
leaving parse_multiple_ranks duration=0.44 seconds
leaving parse_traces duration=0.44 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/resnet50-inference/device.0.json time = 0.01 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/resnet50-inference/device.0.json backend=json in 0.07 seconds; current PID:170154
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/resnet50-inference/device.0.json in 0.09 seconds; current PID:170154
leaving parse_multiple_ranks duration=0.09 seconds
leaving parse_traces duration=0.09 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/bert-inference/device.0.json time = 0.01 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/bert-inference/device.0.json backend=json in 0.06 seconds; current PID:170154
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/bert-inference/device.0.json in 0.08 seconds; current PID:170154
leaving parse_multiple_ranks duration=0.08 seconds
leaving parse_traces duration=0.09 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/deit-inference/device.0.json time = 0.02 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/deit-inference/device.0.json backend=json in 0.07 seconds; current PID:170154
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/deit-inference/device.0.json in 0.09 seconds; current PID:170154
leaving parse_multiple_ranks duration=0.10 seconds
leaving parse_traces duration=0.10 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/bloom-inference/device.0.json time = 0.10 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/bloom-inference/device.0.json backend=json in 0.15 seconds; current PID:170154
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/bloom-inference/device.0.json in 0.18 seconds; current PID:170154
leaving parse_multiple_ranks duration=0.18 seconds
leaving parse_traces duration=0.18 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/bert-train/device.0.json time = 0.17 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/bert-train/device.0.json backend=json in 0.40 seconds; current PID:170154
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/bert-train/device.0.json in 0.46 seconds; current PID:170154
leaving parse_multiple_ranks duration=0.47 seconds
leaving parse_traces duration=0.47 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/gemma-inference/device.0.json time = 0.02 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/gemma-inference/device.0.json backend=json in 0.09 seconds; current PID:170154
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/gemma-inference/device.0.json in 0.12 seconds; current PID:170154
leaving parse_multiple_ranks duration=0.12 seconds
leaving parse_traces duration=0.12 seconds
There is only one iteration in the trace. The analysis result may not be accurate.

[shape: (1_131, 22)
 ┌──────┬───────┬─────┬──────┬───┬─────────────┬───────────────────┬───────────┬────────────────────┐
 │ rank ┆ index ┆ cat ┆ name ┆ … ┆ external_id ┆ index_correlation ┆ iteration ┆ s_name             │
 │ ---  ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---         ┆ ---               ┆ ---       ┆ ---                │
 │ i32  ┆ i16   ┆ i64 ┆ i64  ┆   ┆ i16         ┆ i16               ┆ i8        ┆ str                │
 ╞══════╪═══════╪═════╪══════╪═══╪═════════════╪═══════════════════╪═══════════╪════════════════════╡
 │ 0    ┆ 13921 ┆ 27  ┆ 117  ┆ … ┆ 7           ┆ 13923             ┆ 0         ┆ Memset (Device)    │
 │ 0    ┆ 13938 ┆ 14  ┆ 53   ┆ … ┆ 7           ┆ 13940             ┆ 0         ┆ void implicit_conv │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ olve_sgemm<f…      │
 │ 0    ┆ 13945 ┆ 14  ┆ 13   ┆ … ┆ 10          ┆ 13947             ┆ 0         ┆ void at::native::e │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ lementwise_k…      │
 │ 0    ┆ 13952 ┆ 14  ┆ 50   ┆ … ┆ 19          ┆ 13954             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 13957 ┆ 14  ┆ 157  ┆ … ┆ 20          ┆ 13959             ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ …    ┆ …     ┆ …   ┆ …    ┆ … ┆ …           ┆ …                 ┆ …         ┆ …                  │
 │ 0    ┆ 19352 ┆ 14  ┆ 31   ┆ … ┆ 10585       ┆ 19354             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 19356 ┆ 14  ┆ 31   ┆ … ┆ 10585       ┆ 19358             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 19360 ┆ 14  ┆ 31   ┆ … ┆ 10585       ┆ 19362             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 19364 ┆ 14  ┆ 31   ┆ … ┆ 10585       ┆ 19366             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 19368 ┆ 14  ┆ 31   ┆ … ┆ 10585       ┆ 19370             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 └──────┴───────┴─────┴──────┴───┴─────────────┴───────────────────┴───────────┴────────────────────┘,
 shape: (588, 22)
 ┌──────┬───────┬─────┬──────┬───┬─────────────┬───────────────────┬───────────┬────────────────────┐
 │ rank ┆ index ┆ cat ┆ name ┆ … ┆ external_id ┆ index_correlation ┆ iteration ┆ s_name             │
 │ ---  ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---         ┆ ---               ┆ ---       ┆ ---                │
 │ i32  ┆ i16   ┆ i64 ┆ i64  ┆   ┆ i16         ┆ i16               ┆ i8        ┆ str                │
 ╞══════╪═══════╪═════╪══════╪═══╪═════════════╪═══════════════════╪═══════════╪════════════════════╡
 │ 0    ┆ 3657  ┆ 43  ┆ 47   ┆ … ┆ 7           ┆ 3659              ┆ 0         ┆ Memcpy HtoD        │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ (Pageable ->       │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ Devic…             │
 │ 0    ┆ 3661  ┆ 138 ┆ 35   ┆ … ┆ 7           ┆ 3663              ┆ 0         ┆ Stream Sync        │
 │ 0    ┆ 3665  ┆ 43  ┆ 47   ┆ … ┆ 15          ┆ 3667              ┆ 0         ┆ Memcpy HtoD        │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ (Pageable ->       │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ Devic…             │
 │ 0    ┆ 3669  ┆ 138 ┆ 35   ┆ … ┆ 15          ┆ 3671              ┆ 0         ┆ Stream Sync        │
 │ 0    ┆ 3675  ┆ 43  ┆ 86   ┆ … ┆ 26          ┆ 3677              ┆ 0         ┆ Memcpy DtoH        │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ (Device -> Pinned) │
 │ …    ┆ …     ┆ …   ┆ …    ┆ … ┆ …           ┆ …                 ┆ …         ┆ …                  │
 │ 0    ┆ 6533  ┆ 12  ┆ 61   ┆ … ┆ 2158        ┆ 6535              ┆ 0         ┆ void at::native::u │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ nrolled_elem…      │
 │ 0    ┆ 6537  ┆ 12  ┆ 89   ┆ … ┆ 2159        ┆ 6539              ┆ 0         ┆ void at::native::r │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ educe_kernel…      │
 │ 0    ┆ 6541  ┆ 12  ┆ 71   ┆ … ┆ 2162        ┆ 6543              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ 0    ┆ 6545  ┆ 43  ┆ 86   ┆ … ┆ 2165        ┆ 6547              ┆ 0         ┆ Memcpy DtoH        │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ (Device -> Pinned) │
 │ 0    ┆ 6549  ┆ 138 ┆ 35   ┆ … ┆ 2165        ┆ 6551              ┆ 0         ┆ Stream Sync        │
 └──────┴───────┴─────┴──────┴───┴─────────────┴───────────────────┴───────────┴────────────────────┘,
 shape: (358, 22)
 ┌──────┬───────┬─────┬──────┬───┬─────────────┬───────────────────┬───────────┬────────────────────┐
 │ rank ┆ index ┆ cat ┆ name ┆ … ┆ external_id ┆ index_correlation ┆ iteration ┆ s_name             │
 │ ---  ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---         ┆ ---               ┆ ---       ┆ ---                │
 │ i32  ┆ i16   ┆ i64 ┆ i64  ┆   ┆ i16         ┆ i16               ┆ i8        ┆ str                │
 ╞══════╪═══════╪═════╪══════╪═══╪═════════════╪═══════════════════╪═══════════╪════════════════════╡
 │ 0    ┆ 2744  ┆ 22  ┆ 13   ┆ … ┆ 13          ┆ 2746              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_ga…      │
 │ 0    ┆ 2751  ┆ 22  ┆ 43   ┆ … ┆ 19          ┆ 2753              ┆ 0         ┆ void (anonymous    │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ namespace)::el…    │
 │ 0    ┆ 2758  ┆ 22  ┆ 170  ┆ … ┆ 22          ┆ 2760              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 2762  ┆ 72  ┆ 74   ┆ … ┆ 33          ┆ 2764              ┆ 0         ┆ Memcpy HtoD        │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ (Pageable ->       │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ Devic…             │
 │ 0    ┆ 2766  ┆ 201 ┆ 59   ┆ … ┆ 33          ┆ 2768              ┆ 0         ┆ Stream Sync        │
 │ …    ┆ …     ┆ …   ┆ …    ┆ … ┆ …           ┆ …                 ┆ …         ┆ …                  │
 │ 0    ┆ 4501  ┆ 22  ┆ 40   ┆ … ┆ 2198        ┆ 4503              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 4505  ┆ 22  ┆ 40   ┆ … ┆ 2198        ┆ 4507              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 4509  ┆ 22  ┆ 40   ┆ … ┆ 2198        ┆ 4511              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 4513  ┆ 22  ┆ 40   ┆ … ┆ 2198        ┆ 4515              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 4517  ┆ 22  ┆ 40   ┆ … ┆ 2198        ┆ 4519              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 └──────┴───────┴─────┴──────┴───┴─────────────┴───────────────────┴───────────┴────────────────────┘,
 shape: (962, 22)
 ┌──────┬───────┬─────┬──────┬───┬─────────────┬───────────────────┬───────────┬────────────────────┐
 │ rank ┆ index ┆ cat ┆ name ┆ … ┆ external_id ┆ index_correlation ┆ iteration ┆ s_name             │
 │ ---  ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---         ┆ ---               ┆ ---       ┆ ---                │
 │ i32  ┆ i16   ┆ i64 ┆ i64  ┆   ┆ i16         ┆ i16               ┆ i8        ┆ str                │
 ╞══════╪═══════╪═════╪══════╪═══╪═════════════╪═══════════════════╪═══════════╪════════════════════╡
 │ 0    ┆ 9457  ┆ 32  ┆ 113  ┆ … ┆ 7           ┆ 9459              ┆ 0         ┆ Memset (Device)    │
 │ 0    ┆ 9536  ┆ 16  ┆ 87   ┆ … ┆ 7           ┆ 9538              ┆ 0         ┆ void cask__5x_cudn │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ n::computeOf…      │
 │ 0    ┆ 9547  ┆ 16  ┆ 63   ┆ … ┆ 7           ┆ 9549              ┆ 0         ┆ _5x_cudnn_volta_sc │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ udnn_128x32_…      │
 │ 0    ┆ 9556  ┆ 16  ┆ 26   ┆ … ┆ 8           ┆ 9558              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ 0    ┆ 9563  ┆ 16  ┆ 74   ┆ … ┆ 11          ┆ 9565              ┆ 0         ┆ void cudnn::bn_fw_ │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ tr_1C11_kern…      │
 │ …    ┆ …     ┆ …   ┆ …    ┆ … ┆ …           ┆ …                 ┆ …         ┆ …                  │
 │ 0    ┆ 16864 ┆ 16  ┆ 84   ┆ … ┆ 7025        ┆ 16866             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 16869 ┆ 16  ┆ 34   ┆ … ┆ 7187        ┆ 16871             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 16873 ┆ 16  ┆ 34   ┆ … ┆ 7187        ┆ 16875             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 16877 ┆ 16  ┆ 34   ┆ … ┆ 7187        ┆ 16879             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 16881 ┆ 16  ┆ 34   ┆ … ┆ 7187        ┆ 16883             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 └──────┴───────┴─────┴──────┴───┴─────────────┴───────────────────┴───────────┴────────────────────┘,
 shape: (1_156, 22)
 ┌──────┬───────┬─────┬──────┬───┬─────────────┬───────────────────┬───────────┬────────────────────┐
 │ rank ┆ index ┆ cat ┆ name ┆ … ┆ external_id ┆ index_correlation ┆ iteration ┆ s_name             │
 │ ---  ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---         ┆ ---               ┆ ---       ┆ ---                │
 │ i32  ┆ i16   ┆ i64 ┆ i64  ┆   ┆ i16         ┆ i16               ┆ i8        ┆ str                │
 ╞══════╪═══════╪═════╪══════╪═══╪═════════════╪═══════════════════╪═══════════╪════════════════════╡
 │ 0    ┆ 12124 ┆ 64  ┆ 67   ┆ … ┆ 34          ┆ 12126             ┆ 0         ┆ Memcpy HtoD        │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ (Pageable ->       │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ Devic…             │
 │ 0    ┆ 12128 ┆ 195 ┆ 55   ┆ … ┆ 34          ┆ 12130             ┆ 0         ┆ Stream Sync        │
 │ 0    ┆ 12132 ┆ 64  ┆ 67   ┆ … ┆ 38          ┆ 12134             ┆ 0         ┆ Memcpy HtoD        │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ (Pageable ->       │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ Devic…             │
 │ 0    ┆ 12136 ┆ 195 ┆ 55   ┆ … ┆ 38          ┆ 12138             ┆ 0         ┆ Stream Sync        │
 │ 0    ┆ 12140 ┆ 64  ┆ 67   ┆ … ┆ 42          ┆ 12142             ┆ 0         ┆ Memcpy HtoD        │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ (Pageable ->       │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ Devic…             │
 │ …    ┆ …     ┆ …   ┆ …    ┆ … ┆ …           ┆ …                 ┆ …         ┆ …                  │
 │ 0    ┆ 17762 ┆ 22  ┆ 38   ┆ … ┆ 8857        ┆ 17764             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 17766 ┆ 22  ┆ 38   ┆ … ┆ 8857        ┆ 17768             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 17770 ┆ 22  ┆ 38   ┆ … ┆ 8857        ┆ 17772             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 17774 ┆ 22  ┆ 38   ┆ … ┆ 8857        ┆ 17776             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 17778 ┆ 22  ┆ 38   ┆ … ┆ 8857        ┆ 17780             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 └──────┴───────┴─────┴──────┴───┴─────────────┴───────────────────┴───────────┴────────────────────┘,
 shape: (216, 22)
 ┌──────┬───────┬─────┬──────┬───┬─────────────┬───────────────────┬───────────┬────────────────────┐
 │ rank ┆ index ┆ cat ┆ name ┆ … ┆ external_id ┆ index_correlation ┆ iteration ┆ s_name             │
 │ ---  ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---         ┆ ---               ┆ ---       ┆ ---                │
 │ i32  ┆ i16   ┆ i64 ┆ i64  ┆   ┆ i16         ┆ i16               ┆ i8        ┆ str                │
 ╞══════╪═══════╪═════╪══════╪═══╪═════════════╪═══════════════════╪═══════════╪════════════════════╡
 │ 0    ┆ 1292  ┆ 27  ┆ 26   ┆ … ┆ 6           ┆ 1294              ┆ 0         ┆ Memset (Device)    │
 │ 0    ┆ 1371  ┆ 12  ┆ 1    ┆ … ┆ 6           ┆ 1373              ┆ 0         ┆ void cask__5x_cudn │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ n::computeOf…      │
 │ 0    ┆ 1382  ┆ 12  ┆ 52   ┆ … ┆ 6           ┆ 1384              ┆ 0         ┆ _5x_cudnn_volta_sc │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ udnn_128x32_…      │
 │ 0    ┆ 1391  ┆ 12  ┆ 3    ┆ … ┆ 9           ┆ 1393              ┆ 0         ┆ void cudnn::bn_fw_ │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ inf_1C11_ker…      │
 │ 0    ┆ 1398  ┆ 12  ┆ 20   ┆ … ┆ 17          ┆ 1400              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ …    ┆ …     ┆ …   ┆ …    ┆ … ┆ …           ┆ …                 ┆ …         ┆ …                  │
 │ 0    ┆ 3779  ┆ 12  ┆ 3    ┆ … ┆ 798         ┆ 3781              ┆ 0         ┆ void cudnn::bn_fw_ │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ inf_1C11_ker…      │
 │ 0    ┆ 3783  ┆ 12  ┆ 60   ┆ … ┆ 805         ┆ 3785              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ 0    ┆ 3787  ┆ 12  ┆ 20   ┆ … ┆ 807         ┆ 3789              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ 0    ┆ 3794  ┆ 12  ┆ 58   ┆ … ┆ 809         ┆ 3796              ┆ 0         ┆ void at::native::r │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ educe_kernel…      │
 │ 0    ┆ 3811  ┆ 12  ┆ 5    ┆ … ┆ 816         ┆ 3813              ┆ 0         ┆ void gemv2T_kernel │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ _val<int, in…      │
 └──────┴───────┴─────┴──────┴───┴─────────────┴───────────────────┴───────────┴────────────────────┘,
 shape: (196, 22)
 ┌──────┬───────┬─────┬──────┬───┬─────────────┬───────────────────┬───────────┬────────────────────┐
 │ rank ┆ index ┆ cat ┆ name ┆ … ┆ external_id ┆ index_correlation ┆ iteration ┆ s_name             │
 │ ---  ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---         ┆ ---               ┆ ---       ┆ ---                │
 │ i32  ┆ i16   ┆ i64 ┆ i64  ┆   ┆ i16         ┆ i16               ┆ i8        ┆ str                │
 ╞══════╪═══════╪═════╪══════╪═══╪═════════════╪═══════════════════╪═══════════╪════════════════════╡
 │ 0    ┆ 1896  ┆ 15  ┆ 30   ┆ … ┆ 12          ┆ 1898              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 1900  ┆ 15  ┆ 30   ┆ … ┆ 19          ┆ 1902              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 1907  ┆ 15  ┆ 58   ┆ … ┆ 23          ┆ 1909              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ 0    ┆ 1911  ┆ 15  ┆ 30   ┆ … ┆ 27          ┆ 1913              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 1915  ┆ 15  ┆ 58   ┆ … ┆ 31          ┆ 1917              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ …    ┆ …     ┆ …   ┆ …    ┆ … ┆ …           ┆ …                 ┆ …         ┆ …                  │
 │ 0    ┆ 2957  ┆ 15  ┆ 6    ┆ … ┆ 1317        ┆ 2959              ┆ 0         ┆ void gemv2T_kernel │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ _val<int, in…      │
 │ 0    ┆ 2964  ┆ 15  ┆ 62   ┆ … ┆ 1318        ┆ 2966              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ 0    ┆ 2972  ┆ 15  ┆ 53   ┆ … ┆ 1320        ┆ 2974              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 2981  ┆ 15  ┆ 74   ┆ … ┆ 1329        ┆ 2983              ┆ 0         ┆ void               │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ dot_kernel<float,  │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ 128, 0,…           │
 │ 0    ┆ 2986  ┆ 15  ┆ 7    ┆ … ┆ 1329        ┆ 2988              ┆ 0         ┆ void reduce_1Block │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ _kernel<floa…      │
 └──────┴───────┴─────┴──────┴───┴─────────────┴───────────────────┴───────────┴────────────────────┘,
 shape: (214, 22)
 ┌──────┬───────┬─────┬──────┬───┬─────────────┬───────────────────┬───────────┬────────────────────┐
 │ rank ┆ index ┆ cat ┆ name ┆ … ┆ external_id ┆ index_correlation ┆ iteration ┆ s_name             │
 │ ---  ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---         ┆ ---               ┆ ---       ┆ ---                │
 │ i32  ┆ i16   ┆ i64 ┆ i64  ┆   ┆ i16         ┆ i16               ┆ i8        ┆ str                │
 ╞══════╪═══════╪═════╪══════╪═══╪═════════════╪═══════════════════╪═══════════╪════════════════════╡
 │ 0    ┆ 1729  ┆ 24  ┆ 23   ┆ … ┆ 6           ┆ 1731              ┆ 0         ┆ Memset (Device)    │
 │ 0    ┆ 1746  ┆ 13  ┆ 43   ┆ … ┆ 6           ┆ 1748              ┆ 0         ┆ void implicit_conv │

In [4]:
df = dfs[0].drop("bytes")

In [5]:
df.filter(pl.col("cat") == 132).select("dur").sum()

shape: (1, 1)
┌─────┐
│ dur │
│ --- │
│ f64 │
╞═════╡
│ 0.0 │
└─────┘

In [6]:
[i for i in symbol_table if i == "trace"]

[]

In [7]:
symbol_table.get_sym_id_map()

AttributeError: 'list' object has no attribute 'get_sym_id_map'

In [ ]:
analyzer.t.symbol_table.get_sym_id_map().get("Trace")

In [8]:
df = pl.read_json("/proj/threadtune-PG0/amir/kineto_traces/bert-train/device.0.json").select(pl.col("traceEvents").explode().struct.unnest())

In [9]:
df.filter(pl.col("cat") == "Trace").select("dur")

shape: (1, 1)
┌────────────┐
│ dur        │
│ ---        │
│ f64        │
╞════════════╡
│ 652527.152 │
└────────────┘

In [ ]:
df.filter(pl.col("cat") == "Trace").select("dur") - df.filter(pl.col("cat") == "kernel").select("dur").sum()

shape: (1, 1)
┌───────────┐
│ dur       │
│ ---       │
│ f64       │
╞═══════════╡
│ 20745.858 │
└───────────┘