In [1]:
import polars as pl
import polars.selectors as cs
from hta.trace_analysis import TraceAnalysis
import pandas as pd
import glob
import os

In [2]:
dfs = []
for path in glob.glob("/proj/threadtune-PG0/amir/kineto_traces/*"):
    analyzer = TraceAnalysis({0: "device.0.json"}, path)
    rank = 0
    trace_data = analyzer.t.get_trace(rank)
    symbol_table = analyzer.t.symbol_table.get_sym_table()
    dfs.append(
        pl.concat(
            pl.from_pandas(trace_data[trace_data["stream"] != -1])
            .select(pl.lit(rank).alias("rank"), pl.all())
            for rank, trace_data in analyzer.t.traces.items()
        ).join(
            pl.from_dict({"name": list(range(len(symbol_table))), "s_name": symbol_table}),
            on="name",
        )
    )
dfs

Parsed /proj/threadtune-PG0/amir/kineto_traces/deit-train/device.0.json time = 0.20 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/deit-train/device.0.json backend=json in 0.47 seconds; current PID:572824
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/deit-train/device.0.json in 0.53 seconds; current PID:572824
leaving parse_multiple_ranks duration=0.54 seconds
leaving parse_traces duration=0.54 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/gpt2-inference/device.0.json time = 0.10 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/gpt2-inference/device.0.json backend=json in 0.17 seconds; current PID:572824
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/gpt2-inference/device.0.json in 0.20 seconds; current PID:572824
leaving parse_multiple_ranks duration=0.21 seconds
leaving parse_traces duration=0.21 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/bloom-train/device.0.json time = 0.02 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/bloom-train/device.0.json backend=json in 0.08 seconds; current PID:572824
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/bloom-train/device.0.json in 0.10 seconds; current PID:572824
leaving parse_multiple_ranks duration=0.11 seconds
leaving parse_traces duration=0.11 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/resnet50-train/device.0.json time = 0.14 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/resnet50-train/device.0.json backend=json in 0.32 seconds; current PID:572824
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/resnet50-train/device.0.json in 0.37 seconds; current PID:572824
leaving parse_multiple_ranks duration=0.37 seconds
leaving parse_traces duration=0.37 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/gpt2-train/device.0.json time = 0.24 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/gpt2-train/device.0.json backend=json in 0.44 seconds; current PID:572824
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/gpt2-train/device.0.json in 0.49 seconds; current PID:572824
leaving parse_multiple_ranks duration=0.50 seconds
leaving parse_traces duration=0.50 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/resnet50-inference/device.0.json time = 0.01 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/resnet50-inference/device.0.json backend=json in 0.06 seconds; current PID:572824
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/resnet50-inference/device.0.json in 0.08 seconds; current PID:572824
leaving parse_multiple_ranks duration=0.08 seconds
leaving parse_traces duration=0.08 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/bert-inference/device.0.json time = 0.02 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/bert-inference/device.0.json backend=json in 0.07 seconds; current PID:572824
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/bert-inference/device.0.json in 0.09 seconds; current PID:572824
leaving parse_multiple_ranks duration=0.10 seconds
leaving parse_traces duration=0.10 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/deit-inference/device.0.json time = 0.01 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/deit-inference/device.0.json backend=json in 0.06 seconds; current PID:572824
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/deit-inference/device.0.json in 0.08 seconds; current PID:572824
leaving parse_multiple_ranks duration=0.08 seconds
leaving parse_traces duration=0.08 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/bloom-inference/device.0.json time = 0.02 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/bloom-inference/device.0.json backend=json in 0.08 seconds; current PID:572824
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/bloom-inference/device.0.json in 0.10 seconds; current PID:572824
leaving parse_multiple_ranks duration=0.10 seconds
leaving parse_traces duration=0.11 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/bert-train/device.0.json time = 0.23 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/bert-train/device.0.json backend=json in 0.45 seconds; current PID:572824
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/bert-train/device.0.json in 0.51 seconds; current PID:572824
leaving parse_multiple_ranks duration=0.52 seconds
leaving parse_traces duration=0.52 seconds
There is only one iteration in the trace. The analysis result may not be accurate.
Parsed /proj/threadtune-PG0/amir/kineto_traces/gemma-inference/device.0.json time = 0.02 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/gemma-inference/device.0.json backend=json in 0.09 seconds; current PID:572824
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/gemma-inference/device.0.json in 0.11 seconds; current PID:572824
leaving parse_multiple_ranks duration=0.12 seconds
leaving parse_traces duration=0.12 seconds
There is only one iteration in the trace. The analysis result may not be accurate.

[shape: (1_131, 22)
 ┌──────┬───────┬─────┬──────┬───┬─────────────┬───────────────────┬───────────┬────────────────────┐
 │ rank ┆ index ┆ cat ┆ name ┆ … ┆ external_id ┆ index_correlation ┆ iteration ┆ s_name             │
 │ ---  ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---         ┆ ---               ┆ ---       ┆ ---                │
 │ i32  ┆ i16   ┆ i64 ┆ i64  ┆   ┆ i16         ┆ i16               ┆ i8        ┆ str                │
 ╞══════╪═══════╪═════╪══════╪═══╪═════════════╪═══════════════════╪═══════════╪════════════════════╡
 │ 0    ┆ 13921 ┆ 68  ┆ 184  ┆ … ┆ 7           ┆ 13923             ┆ 0         ┆ Memset (Device)    │
 │ 0    ┆ 13938 ┆ 97  ┆ 163  ┆ … ┆ 7           ┆ 13940             ┆ 0         ┆ void implicit_conv │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ olve_sgemm<f…      │
 │ 0    ┆ 13945 ┆ 97  ┆ 114  ┆ … ┆ 10          ┆ 13947             ┆ 0         ┆ void at::native::e │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ lementwise_k…      │
 │ 0    ┆ 13952 ┆ 97  ┆ 137  ┆ … ┆ 19          ┆ 13954             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 13957 ┆ 97  ┆ 91   ┆ … ┆ 20          ┆ 13959             ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ …    ┆ …     ┆ …   ┆ …    ┆ … ┆ …           ┆ …                 ┆ …         ┆ …                  │
 │ 0    ┆ 19352 ┆ 97  ┆ 139  ┆ … ┆ 10585       ┆ 19354             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 19356 ┆ 97  ┆ 139  ┆ … ┆ 10585       ┆ 19358             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 19360 ┆ 97  ┆ 139  ┆ … ┆ 10585       ┆ 19362             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 19364 ┆ 97  ┆ 139  ┆ … ┆ 10585       ┆ 19366             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 19368 ┆ 97  ┆ 139  ┆ … ┆ 10585       ┆ 19370             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 └──────┴───────┴─────┴──────┴───┴─────────────┴───────────────────┴───────────┴────────────────────┘,
 shape: (588, 22)
 ┌──────┬───────┬─────┬──────┬───┬─────────────┬───────────────────┬───────────┬────────────────────┐
 │ rank ┆ index ┆ cat ┆ name ┆ … ┆ external_id ┆ index_correlation ┆ iteration ┆ s_name             │
 │ ---  ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---         ┆ ---               ┆ ---       ┆ ---                │
 │ i32  ┆ i16   ┆ i64 ┆ i64  ┆   ┆ i16         ┆ i16               ┆ i8        ┆ str                │
 ╞══════╪═══════╪═════╪══════╪═══╪═════════════╪═══════════════════╪═══════════╪════════════════════╡
 │ 0    ┆ 3657  ┆ 51  ┆ 61   ┆ … ┆ 7           ┆ 3659              ┆ 0         ┆ Memcpy HtoD        │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ (Pageable ->       │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ Devic…             │
 │ 0    ┆ 3661  ┆ 76  ┆ 124  ┆ … ┆ 7           ┆ 3663              ┆ 0         ┆ Stream Sync        │
 │ 0    ┆ 3665  ┆ 51  ┆ 61   ┆ … ┆ 15          ┆ 3667              ┆ 0         ┆ Memcpy HtoD        │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ (Pageable ->       │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ Devic…             │
 │ 0    ┆ 3669  ┆ 76  ┆ 124  ┆ … ┆ 15          ┆ 3671              ┆ 0         ┆ Stream Sync        │
 │ 0    ┆ 3675  ┆ 51  ┆ 90   ┆ … ┆ 26          ┆ 3677              ┆ 0         ┆ Memcpy DtoH        │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ (Device -> Pinned) │
 │ …    ┆ …     ┆ …   ┆ …    ┆ … ┆ …           ┆ …                 ┆ …         ┆ …                  │
 │ 0    ┆ 6533  ┆ 86  ┆ 97   ┆ … ┆ 2158        ┆ 6535              ┆ 0         ┆ void at::native::u │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ nrolled_elem…      │
 │ 0    ┆ 6537  ┆ 86  ┆ 131  ┆ … ┆ 2159        ┆ 6539              ┆ 0         ┆ void at::native::r │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ educe_kernel…      │
 │ 0    ┆ 6541  ┆ 86  ┆ 145  ┆ … ┆ 2162        ┆ 6543              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ 0    ┆ 6545  ┆ 51  ┆ 90   ┆ … ┆ 2165        ┆ 6547              ┆ 0         ┆ Memcpy DtoH        │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ (Device -> Pinned) │
 │ 0    ┆ 6549  ┆ 76  ┆ 124  ┆ … ┆ 2165        ┆ 6551              ┆ 0         ┆ Stream Sync        │
 └──────┴───────┴─────┴──────┴───┴─────────────┴───────────────────┴───────────┴────────────────────┘,
 shape: (358, 22)
 ┌──────┬───────┬─────┬──────┬───┬─────────────┬───────────────────┬───────────┬────────────────────┐
 │ rank ┆ index ┆ cat ┆ name ┆ … ┆ external_id ┆ index_correlation ┆ iteration ┆ s_name             │
 │ ---  ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---         ┆ ---               ┆ ---       ┆ ---                │
 │ i32  ┆ i16   ┆ i64 ┆ i64  ┆   ┆ i16         ┆ i16               ┆ i8        ┆ str                │
 ╞══════╪═══════╪═════╪══════╪═══╪═════════════╪═══════════════════╪═══════════╪════════════════════╡
 │ 0    ┆ 2744  ┆ 115 ┆ 73   ┆ … ┆ 13          ┆ 2746              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_ga…      │
 │ 0    ┆ 2751  ┆ 115 ┆ 193  ┆ … ┆ 19          ┆ 2753              ┆ 0         ┆ void (anonymous    │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ namespace)::el…    │
 │ 0    ┆ 2758  ┆ 115 ┆ 203  ┆ … ┆ 22          ┆ 2760              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 2762  ┆ 74  ┆ 87   ┆ … ┆ 33          ┆ 2764              ┆ 0         ┆ Memcpy HtoD        │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ (Pageable ->       │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ Devic…             │
 │ 0    ┆ 2766  ┆ 104 ┆ 175  ┆ … ┆ 33          ┆ 2768              ┆ 0         ┆ Stream Sync        │
 │ …    ┆ …     ┆ …   ┆ …    ┆ … ┆ …           ┆ …                 ┆ …         ┆ …                  │
 │ 0    ┆ 4501  ┆ 115 ┆ 157  ┆ … ┆ 2198        ┆ 4503              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 4505  ┆ 115 ┆ 157  ┆ … ┆ 2198        ┆ 4507              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 4509  ┆ 115 ┆ 157  ┆ … ┆ 2198        ┆ 4511              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 4513  ┆ 115 ┆ 157  ┆ … ┆ 2198        ┆ 4515              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 4517  ┆ 115 ┆ 157  ┆ … ┆ 2198        ┆ 4519              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 └──────┴───────┴─────┴──────┴───┴─────────────┴───────────────────┴───────────┴────────────────────┘,
 shape: (962, 22)
 ┌──────┬───────┬─────┬──────┬───┬─────────────┬───────────────────┬───────────┬────────────────────┐
 │ rank ┆ index ┆ cat ┆ name ┆ … ┆ external_id ┆ index_correlation ┆ iteration ┆ s_name             │
 │ ---  ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---         ┆ ---               ┆ ---       ┆ ---                │
 │ i32  ┆ i16   ┆ i64 ┆ i64  ┆   ┆ i16         ┆ i16               ┆ i8        ┆ str                │
 ╞══════╪═══════╪═════╪══════╪═══╪═════════════╪═══════════════════╪═══════════╪════════════════════╡
 │ 0    ┆ 9457  ┆ 60  ┆ 181  ┆ … ┆ 7           ┆ 9459              ┆ 0         ┆ Memset (Device)    │
 │ 0    ┆ 9536  ┆ 88  ┆ 66   ┆ … ┆ 7           ┆ 9538              ┆ 0         ┆ void cask__5x_cudn │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ n::computeOf…      │
 │ 0    ┆ 9547  ┆ 88  ┆ 109  ┆ … ┆ 7           ┆ 9549              ┆ 0         ┆ _5x_cudnn_volta_sc │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ udnn_128x32_…      │
 │ 0    ┆ 9556  ┆ 88  ┆ 4    ┆ … ┆ 8           ┆ 9558              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ 0    ┆ 9563  ┆ 88  ┆ 175  ┆ … ┆ 11          ┆ 9565              ┆ 0         ┆ void cudnn::bn_fw_ │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ tr_1C11_kern…      │
 │ …    ┆ …     ┆ …   ┆ …    ┆ … ┆ …           ┆ …                 ┆ …         ┆ …                  │
 │ 0    ┆ 16864 ┆ 88  ┆ 72   ┆ … ┆ 7025        ┆ 16866             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 16869 ┆ 88  ┆ 129  ┆ … ┆ 7187        ┆ 16871             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 16873 ┆ 88  ┆ 129  ┆ … ┆ 7187        ┆ 16875             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 16877 ┆ 88  ┆ 129  ┆ … ┆ 7187        ┆ 16879             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 16881 ┆ 88  ┆ 129  ┆ … ┆ 7187        ┆ 16883             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 └──────┴───────┴─────┴──────┴───┴─────────────┴───────────────────┴───────────┴────────────────────┘,
 shape: (1_156, 22)
 ┌──────┬───────┬─────┬──────┬───┬─────────────┬───────────────────┬───────────┬────────────────────┐
 │ rank ┆ index ┆ cat ┆ name ┆ … ┆ external_id ┆ index_correlation ┆ iteration ┆ s_name             │
 │ ---  ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---         ┆ ---               ┆ ---       ┆ ---                │
 │ i32  ┆ i16   ┆ i64 ┆ i64  ┆   ┆ i16         ┆ i16               ┆ i8        ┆ str                │
 ╞══════╪═══════╪═════╪══════╪═══╪═════════════╪═══════════════════╪═══════════╪════════════════════╡
 │ 0    ┆ 12124 ┆ 76  ┆ 90   ┆ … ┆ 34          ┆ 12126             ┆ 0         ┆ Memcpy HtoD        │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ (Pageable ->       │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ Devic…             │
 │ 0    ┆ 12128 ┆ 106 ┆ 170  ┆ … ┆ 34          ┆ 12130             ┆ 0         ┆ Stream Sync        │
 │ 0    ┆ 12132 ┆ 76  ┆ 90   ┆ … ┆ 38          ┆ 12134             ┆ 0         ┆ Memcpy HtoD        │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ (Pageable ->       │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ Devic…             │
 │ 0    ┆ 12136 ┆ 106 ┆ 170  ┆ … ┆ 38          ┆ 12138             ┆ 0         ┆ Stream Sync        │
 │ 0    ┆ 12140 ┆ 76  ┆ 90   ┆ … ┆ 42          ┆ 12142             ┆ 0         ┆ Memcpy HtoD        │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ (Pageable ->       │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ Devic…             │
 │ …    ┆ …     ┆ …   ┆ …    ┆ … ┆ …           ┆ …                 ┆ …         ┆ …                  │
 │ 0    ┆ 17762 ┆ 118 ┆ 157  ┆ … ┆ 8857        ┆ 17764             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 17766 ┆ 118 ┆ 157  ┆ … ┆ 8857        ┆ 17768             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 17770 ┆ 118 ┆ 157  ┆ … ┆ 8857        ┆ 17772             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 17774 ┆ 118 ┆ 157  ┆ … ┆ 8857        ┆ 17776             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 17778 ┆ 118 ┆ 157  ┆ … ┆ 8857        ┆ 17780             ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 └──────┴───────┴─────┴──────┴───┴─────────────┴───────────────────┴───────────┴────────────────────┘,
 shape: (216, 22)
 ┌──────┬───────┬─────┬──────┬───┬─────────────┬───────────────────┬───────────┬────────────────────┐
 │ rank ┆ index ┆ cat ┆ name ┆ … ┆ external_id ┆ index_correlation ┆ iteration ┆ s_name             │
 │ ---  ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---         ┆ ---               ┆ ---       ┆ ---                │
 │ i32  ┆ i16   ┆ i64 ┆ i64  ┆   ┆ i16         ┆ i16               ┆ i8        ┆ str                │
 ╞══════╪═══════╪═════╪══════╪═══╪═════════════╪═══════════════════╪═══════════╪════════════════════╡
 │ 0    ┆ 1292  ┆ 56  ┆ 75   ┆ … ┆ 6           ┆ 1294              ┆ 0         ┆ Memset (Device)    │
 │ 0    ┆ 1371  ┆ 5   ┆ 60   ┆ … ┆ 6           ┆ 1373              ┆ 0         ┆ void cask__5x_cudn │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ n::computeOf…      │
 │ 0    ┆ 1382  ┆ 5   ┆ 19   ┆ … ┆ 6           ┆ 1384              ┆ 0         ┆ _5x_cudnn_volta_sc │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ udnn_128x32_…      │
 │ 0    ┆ 1391  ┆ 5   ┆ 38   ┆ … ┆ 9           ┆ 1393              ┆ 0         ┆ void cudnn::bn_fw_ │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ inf_1C11_ker…      │
 │ 0    ┆ 1398  ┆ 5   ┆ 20   ┆ … ┆ 17          ┆ 1400              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ …    ┆ …     ┆ …   ┆ …    ┆ … ┆ …           ┆ …                 ┆ …         ┆ …                  │
 │ 0    ┆ 3779  ┆ 5   ┆ 38   ┆ … ┆ 798         ┆ 3781              ┆ 0         ┆ void cudnn::bn_fw_ │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ inf_1C11_ker…      │
 │ 0    ┆ 3783  ┆ 5   ┆ 73   ┆ … ┆ 805         ┆ 3785              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ 0    ┆ 3787  ┆ 5   ┆ 20   ┆ … ┆ 807         ┆ 3789              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ 0    ┆ 3794  ┆ 5   ┆ 22   ┆ … ┆ 809         ┆ 3796              ┆ 0         ┆ void at::native::r │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ educe_kernel…      │
 │ 0    ┆ 3811  ┆ 5   ┆ 66   ┆ … ┆ 816         ┆ 3813              ┆ 0         ┆ void gemv2T_kernel │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ _val<int, in…      │
 └──────┴───────┴─────┴──────┴───┴─────────────┴───────────────────┴───────────┴────────────────────┘,
 shape: (196, 22)
 ┌──────┬───────┬─────┬──────┬───┬─────────────┬───────────────────┬───────────┬────────────────────┐
 │ rank ┆ index ┆ cat ┆ name ┆ … ┆ external_id ┆ index_correlation ┆ iteration ┆ s_name             │
 │ ---  ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---         ┆ ---               ┆ ---       ┆ ---                │
 │ i32  ┆ i16   ┆ i64 ┆ i64  ┆   ┆ i16         ┆ i16               ┆ i8        ┆ str                │
 ╞══════╪═══════╪═════╪══════╪═══╪═════════════╪═══════════════════╪═══════════╪════════════════════╡
 │ 0    ┆ 1896  ┆ 6   ┆ 59   ┆ … ┆ 12          ┆ 1898              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 1900  ┆ 6   ┆ 59   ┆ … ┆ 19          ┆ 1902              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 1907  ┆ 6   ┆ 73   ┆ … ┆ 23          ┆ 1909              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ 0    ┆ 1911  ┆ 6   ┆ 59   ┆ … ┆ 27          ┆ 1913              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 1915  ┆ 6   ┆ 73   ┆ … ┆ 31          ┆ 1917              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ …    ┆ …     ┆ …   ┆ …    ┆ … ┆ …           ┆ …                 ┆ …         ┆ …                  │
 │ 0    ┆ 2957  ┆ 6   ┆ 69   ┆ … ┆ 1317        ┆ 2959              ┆ 0         ┆ void gemv2T_kernel │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ _val<int, in…      │
 │ 0    ┆ 2964  ┆ 6   ┆ 52   ┆ … ┆ 1318        ┆ 2966              ┆ 0         ┆ void at::native::v │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ ectorized_el…      │
 │ 0    ┆ 2972  ┆ 6   ┆ 7    ┆ … ┆ 1320        ┆ 2974              ┆ 0         ┆ void at::native::( │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ anonymous na…      │
 │ 0    ┆ 2981  ┆ 6   ┆ 49   ┆ … ┆ 1329        ┆ 2983              ┆ 0         ┆ void               │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ dot_kernel<float,  │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ 128, 0,…           │
 │ 0    ┆ 2986  ┆ 6   ┆ 53   ┆ … ┆ 1329        ┆ 2988              ┆ 0         ┆ void reduce_1Block │
 │      ┆       ┆     ┆      ┆   ┆             ┆                   ┆           ┆ _kernel<floa…      │
 └──────┴───────┴─────┴──────┴───┴─────────────┴───────────────────┴───────────┴────────────────────┘,
 shape: (214, 22)
 ┌──────┬───────┬─────┬──────┬───┬─────────────┬───────────────────┬───────────┬────────────────────┐
 │ rank ┆ index ┆ cat ┆ name ┆ … ┆ external_id ┆ index_correlation ┆ iteration ┆ s_name             │
 │ ---  ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---         ┆ ---               ┆ ---       ┆ ---                │
 │ i32  ┆ i16   ┆ i64 ┆ i64  ┆   ┆ i16         ┆ i16               ┆ i8        ┆ str                │
 ╞══════╪═══════╪═════╪══════╪═══╪═════════════╪═══════════════════╪═══════════╪════════════════════╡
 │ 0    ┆ 1729  ┆ 50  ┆ 70   ┆ … ┆ 6           ┆ 1731              ┆ 0         ┆ Memset (Device)    │
 │ 0    ┆ 1746  ┆ 4   ┆ 48   ┆ … ┆ 6           ┆ 1748              ┆ 0         ┆ void implicit_conv │

In [39]:
analyzer = TraceAnalysis({0: "device.0.json"}, "/proj/threadtune-PG0/amir/kineto_traces/bert-inference/")
rank = 0
trace_data = analyzer.t.get_trace(rank)
symbol_table = analyzer.t.symbol_table.get_sym_table()
trace_df = pl.concat(
    pl.from_pandas(trace_data[trace_data["stream"] != -1][["name", "dur"]])
    .select(pl.lit(rank).alias("rank"), pl.all())
    for rank, trace_data in analyzer.t.traces.items()
).join(
    pl.from_dict({"name": list(range(len(symbol_table))), "s_name": symbol_table}),
    on="name",
).filter(
    ~pl.col("s_name").str.starts_with("nccl") & 
    ~pl.col("s_name").is_in([
        "Stream Sync",
        "Memcpy DtoD (Device -> Device)",
        "Memcpy HtoD (Pageable -> Device)",
        "Memcpy DtoH (Device -> Pinned)",
    ])
).select(pl.lit("bert").alias("model"), pl.all())
trace_df

Parsed /proj/threadtune-PG0/amir/kineto_traces/bert-inference/device.0.json time = 0.04 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /proj/threadtune-PG0/amir/kineto_traces/bert-inference/device.0.json backend=json in 0.13 seconds; current PID:572824
Overall parsing of /proj/threadtune-PG0/amir/kineto_traces/bert-inference/device.0.json in 0.15 seconds; current PID:572824
leaving parse_multiple_ranks duration=0.16 seconds
leaving parse_traces duration=0.16 seconds
There is only one iteration in the trace. The analysis result may not be accurate.

shape: (194, 5)
┌───────┬──────┬──────┬─────┬─────────────────────────────────┐
│ model ┆ rank ┆ name ┆ dur ┆ s_name                          │
│ ---   ┆ ---  ┆ ---  ┆ --- ┆ ---                             │
│ str   ┆ i32  ┆ i64  ┆ f64 ┆ str                             │
╞═══════╪══════╪══════╪═════╪═════════════════════════════════╡
│ bert  ┆ 0    ┆ 59   ┆ 9.0 ┆ void at::native::(anonymous na… │
│ bert  ┆ 0    ┆ 59   ┆ 4.0 ┆ void at::native::(anonymous na… │
│ bert  ┆ 0    ┆ 73   ┆ 1.0 ┆ void at::native::vectorized_el… │
│ bert  ┆ 0    ┆ 59   ┆ 7.0 ┆ void at::native::(anonymous na… │
│ bert  ┆ 0    ┆ 73   ┆ 0.0 ┆ void at::native::vectorized_el… │
│ …     ┆ …    ┆ …    ┆ …   ┆ …                               │
│ bert  ┆ 0    ┆ 69   ┆ 7.0 ┆ void gemv2T_kernel_val<int, in… │
│ bert  ┆ 0    ┆ 52   ┆ 2.0 ┆ void at::native::vectorized_el… │
│ bert  ┆ 0    ┆ 7    ┆ 3.0 ┆ void at::native::(anonymous na… │
│ bert  ┆ 0    ┆ 49   ┆ 2.0 ┆ void dot_kernel<float, 128, 0,… │
│ bert  ┆ 0    ┆ 53   ┆ 2.0 ┆ void reduce_1Block_kernel<floa… │
└───────┴──────┴──────┴─────┴─────────────────────────────────┘

In [40]:
accel_df = pl.read_csv(
    "/users/zarand1a/accel-sim-framework/kernel_times.csv",
).select(
    pl.col("benchmark").alias("model"),
    pl.col("kernel_demangled").str.strip_chars().alias("kernel"),
    (pl.col("cycle") / 1132).alias("accel_time_us"),
)

In [47]:
accel_df.filter(pl.col("model") == "bert").write_csv("accel_time.csv")

In [26]:
accel_df.filter(pl.col("model") == "bert")

shape: (215, 3)
┌───────┬─────────────────────────────────┬───────────────┐
│ model ┆ kernel                          ┆ accel_time_us │
│ ---   ┆ ---                             ┆ ---           │
│ str   ┆ str                             ┆ f64           │
╞═══════╪═════════════════════════════════╪═══════════════╡
│ bert  ┆ void at::native::<unnamed>::in… ┆ 9.166078      │
│ bert  ┆ void at::native::<unnamed>::in… ┆ 7.567138      │
│ bert  ┆ void at::native::vectorized_el… ┆ 5.09894       │
│ bert  ┆ void at::native::<unnamed>::in… ┆ 9.189046      │
│ bert  ┆ void at::native::vectorized_el… ┆ 5.09894       │
│ …     ┆ …                               ┆ …             │
│ bert  ┆ void at::native::vectorized_el… ┆ 4.864841      │
│ bert  ┆ void at::native::vectorized_el… ┆ 5.137809      │
│ bert  ┆ void at::native::vectorized_el… ┆ 4.948763      │
│ bert  ┆ void at::native::vectorized_el… ┆ 4.948763      │
│ bert  ┆ void at::native::vectorized_el… ┆ 4.935512      │
└───────┴─────────────────────────────────┴───────────────┘

In [46]:
(trace_data["cat"] == 33).sum()

np.int64(1327)

In [21]:
accel_df.join(
    trace_df.select("model", pl.col("s_name").alias("kernel"), pl.col("dur").alias("trace_time_us")),
    on=["model", "kernel"],
)

shape: (0, 4)
┌───────┬────────┬───────────────┬───────────────┐
│ model ┆ kernel ┆ accel_time_us ┆ trace_time_us │
│ ---   ┆ ---    ┆ ---           ┆ ---           │
│ str   ┆ str    ┆ f64           ┆ f64           │
╞═══════╪════════╪═══════════════╪═══════════════╡
└───────┴────────┴───────────────┴───────────────┘

In [49]:
trace_df.select("model", pl.col("s_name").alias("kernel"), pl.col("dur").alias("trace_time_us")).write_csv("trace_time.csv")